FROM node:14-buster-slim as build

WORKDIR /app

COPY . .

RUN yarn

RUN yarn build

FROM nginx:1.18.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
